# This is a basic workflow to help you get started with Actions

name: CI to middleware

# Controls when the action will run. 
on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development
jobs:
  erica_job:
    runs-on: ubuntu-latest
    name: A job to build and push docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Read secrets from AWS Secrets Manager into environment variables
        uses: say8425/aws-secrets-manager-actions@v2
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
          SECRET_NAME: Boat_middleware_service
          OUTPUT_PATH: 'application.properties' # optional
      - name: Copy env files 
        run: "cp  application.properties src/main/resources/application.properties"
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Build with Maven
        run: mvn  clean package -Dmaven.test.skip=true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN}}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: weareboat/middleware:latest
          no-cache: true
          
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

